### ISSUE TITLE
How to intercept menu choice?

### ISSUE THREAD

**Issue by caBBAlainB** [CWSpear/bootstrap-hover-dropdown#112]
Hi,

I try to intercept the clicked choice but I don't know if I made a big mistake or if something prevents it.

Can you please have a look here? http://jsfiddle.net/caBBAlainB/7n0e2cwe/

Regards,
Alain

**Comment by CWSpear** [comment]
A few issues:

That dropdown doesn't have a `change` event, so your fiddle is never going to alert. This has nothing to do with my plugin tho.

The reason the dropdowns aren't working on hover, is because you haven't included my plugin into the fiddle. You tried, but you failed. You linked to the GitHub page for the file, which is much more than "just the source" so it isn't being interpreted correctly.

GitHub *has* raw views for source, but they are blocked from loading stuff like JS. In the future, you can use a service like https://rawgit.com/ or find it on one of the existing CDNs.

**Comment by caBBAlainB** [comment]
Hello,
Thanks a lot, you are right and I successfully got it working with a onclick event.
Regards,
Alain
